name: Bug report - CAPA (New)
description: Tell us about a problem you are experiencing in CAPA
labels: [kind/bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: What steps did you take and what happened
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you expect to happen
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else you would like to add
    description: Miscellaneous information that will assist in solving the issue.
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## Environment
- type: input
  attributes:
    label: Cluster-api-provider-aws version
  validations:
    required: true
- type: input
  attributes:
    label: Kubernetes version
    description: "(use `kubectl version`)"
  validations:
    required: false
- type: input
  attributes:
    label: OS
    description: "(e.g. from `/etc/os-release`)"
  validations:
    required: false